"""empty message

Revision ID: f0b8f95b3437
Revises: f0fb1cd15e6f
Create Date: 2022-08-12 09:16:59.756860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b8f95b3437'
down_revision = 'f0fb1cd15e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('imageURL', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'imageURL')
    # ### end Alembic commands ###
